version: '3.5'

services:

  api:
    build:
        context: ./
        dockerfile: Dockerfile.dev
    volumes:
      - api_sync:/var/www/html:nocopy
    ports:
      - "1000:80"
    links:
      - database
    environment:
      - DB_HOST=database
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=subscribersfields
      - DB_PORT=3306

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=subscribersfields
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  api_sync:
    external: true
  mysql_data:
    driver: local